config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :forms do
    resources :submissions
  end
  resources :domains
  resources :abilities
  resources :abilitysets
  resources :masteries
  resources :contacts, path: '/account/contacts'
  resources :links
  resources :locations
  resources :events do
    collection do
      get 'list'
      get 'tasks'
      get 'calendar'
      get 'log'
      get ':id/participants', to: 'events#participants', as: :participants
      get ':id/login',  to: 'events#login',  as: :login
      get ':id/logout', to: 'events#logout', as: :logout
      patch ':id/login',  to: 'events#login_update', as: :login_update
      patch ':id/logout',  to: 'events#logout_update', as: :logout_update
      patch 'login',  to: 'events#login_updates', as: :login_updates
      patch 'logout',  to: 'events#logout_updates', as: :logout_updates
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      delete :empty_trash
    end
  end

  resources :notes
  get 'dashboard/index'
  get 'conversations/load_messages'
  get "mail" => "mailbox#inbox", as: :mailbox
  get "mail/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mail/sent" => "mailbox#sent", as: :mailbox_sent
  get "mail/trash" => "mailbox#trash", as: :mailbox_trash

  resources :users do
    member do
      put :activate
      put :deactivate
      get :mastery
      get :contacts
      put :update_mastery
    end
  end
  devise_for :users, :path => '/account'
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      root :to => 'dashboard#index'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
.page-header
  %h2= t('.title')
%br
-if current_user
  .btn-group.btn-group-justified
    -if current_user.use_events?
      .btn.btn-default
        = link_to(events_path, 'data-turbolinks' => false) do
          %center
            =icon('calendar', class: 'fa-5x')
            %p= t('events.index.title')
    -if current_user.use_notes?
      .btn.btn-default
        = link_to(notes_path) do
          %center
            =icon('file-text', class: 'fa-5x')
            %p= t('notes.index.title')
    -if current_user.use_mail?
      .btn.btn-default
        = link_to(mailbox_path) do
          %center
            =icon('envelope', class: 'fa-5x')
            %p= t('mailbox.index.title')
  .btn-group.btn-group-justified
    -if current_user.use_user_directory?
      .btn.btn-default
        = link_to(users_path) do
          %center
            =icon('users', class: 'fa-5x')
            %p= t('users.index.title')
    -if current_user.use_links?
      .btn.btn-default
        = link_to(links_path) do
          %center
            =icon('link', class: 'fa-5x')
            %p= t('links.index.title')
    -if current_user.use_locations?
      .btn.btn-default
        = link_to(locations_path) do
          %center
            =icon('globe', class: 'fa-5x')
            %p= t('locations.index.title')
  .btn-group.btn-group-justified
    -if current_user.use_mastery_builder?
      .btn.btn-default
        = link_to(abilities_path) do
          %center
            =icon('cube', class: 'fa-5x')
            %p= t('abilities.index.title')
      .btn.btn-default
        = link_to(abilitysets_path) do
          %center
            =icon('cubes', class: 'fa-5x')
            %p= t('abilitysets.index.title')
      .btn.btn-default
        = link_to(masteries_path) do
          %center
            =icon('university', class: 'fa-5x')
            %p= t('masteries.index.title')
  .btn-group.btn-group-justified
    -if current_user.admin?
      .btn.btn-default
        = link_to(domains_path) do
          %center
            =icon('circle-o', class: 'fa-5x')
            %p= t('domains.index.title')
      .btn.btn-default
        = link_to(roles_path) do
          %center
            =icon('id-badge', class: 'fa-5x')
            %p= t('roles.index.title')
    -if current_user.use_forms?
      .btn.btn-default
        = link_to(forms_path) do
          %center
            =icon('wpforms', class: 'fa-5x')
            %p= t('forms.index.title')
  .btn-group.btn-group-justified
    -if current_user.has_mastery?
      .btn.btn-default
        = link_to(mastery_user_path(current_user)) do
          %center
            =icon('graduation-cap', class: 'fa-5x')
            %p= t('users.mastery.title')