config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :forms do
    resources :submissions
  end
  resources :domains
  resources :abilities
  resources :abilitysets
  resources :masteries
  resources :contacts, path: '/account/contacts'
  resources :links
  resources :locations
  resources :events do
    collection do
      get 'list'
      get 'tasks'
      get 'calendar'
      get 'log'
      get ':id/participants', to: 'events#participants', as: :participants
      get ':id/login',  to: 'events#login',  as: :login
      get ':id/logout', to: 'events#logout', as: :logout
      patch ':id/login',  to: 'events#login_update', as: :login_update
      patch ':id/logout',  to: 'events#logout_update', as: :logout_update
      patch 'login',  to: 'events#login_updates', as: :login_updates
      patch 'logout',  to: 'events#logout_updates', as: :logout_updates
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      delete :empty_trash
    end
  end

  resources :notes
  get 'dashboard/index'
  get 'conversations/load_messages'
  get "mail" => "mailbox#inbox", as: :mailbox
  get "mail/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mail/sent" => "mailbox#sent", as: :mailbox_sent
  get "mail/trash" => "mailbox#trash", as: :mailbox_trash

  resources :users do
    member do
      put :activate
      put :deactivate
      get :mastery
      get :contacts
      put :update_mastery
    end
  end
  devise_for :users, :path => '/account'
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      root :to => 'dashboard#index'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :usable?
  def new
  end

  def index
    redirect_to mailbox_inbox_path
  end
  def create
    if !conversation_params[:recipients].empty? && !conversation_params[:body].empty? && !conversation_params[:subject].empty?
      recipients = User.where(id: conversation_params[:recipients])
      conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
      flash[:notice] = t('.notice')
      redirect_to conversation_path(conversation)
    else
      flash[:alert] = t('.error')
      render :action => :new
    end
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at DESC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = t('.notice')
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  def empty_trash
    current_user.mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(:deleted => true)
    end
    redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def usable?
    unless current_user.use_mail?
      redirect_to root_path, :flash => { :danger => t('access_denied') }
    end
  end
  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.panel.panel-default
  .panel-heading.clearfix
    - if conversation.is_trashed?(current_user)
      = link_to icon('undo'), untrash_conversation_path(conversation), class: 'btn btn-default', method: :post
    - else
      = link_to icon('trash'), trash_conversation_path(conversation), class: 'btn btn-default', method: :post, |
      data: {confirm: t('devise.registrations.edit.are_you_sure')} |
    .pull-right= link_to icon('eye'), conversation_path(conversation), class: 'btn btn-default'
  .panel-body
    .row
      .col-lg-2.col-md-2.col-sm-2.col-xs-4
        %center
          .widewrapper= link_to image_tag(avatar_thumb(conversation.originator)), conversation_path(conversation)
      .col-lg-10.col-md-10.col-sm-10.col-xs-8
        %b= conversation.originator.identifier
        %br
        = t('conversations.model.subject')
        = conversation.subject.html_safe
        %br
        = t('conversations.model.date')
        =l conversation.messages.last.created_at, format: :long

app/views/conversations/_form.html.haml
= link_to icon('arrow-left'), mailbox_path, class: 'btn btn-default'
%br
%br
.panel
  = form_for :conversation, url: :conversations, html: { class: "" } do |f|
    .panel-heading.clearfix
      .action
        .pull-right= f.button icon('paper-plane'), class: "btn btn-default"
    .panel-footer
      .form-group
        %label= t('conversations.model.recipients')
        =#= f.select(:recipients, options_from_collection_for_select(User.all, 'id', 'identifier'), {}, { multiple: true , class: "form-control" })
        = select_tag 'conversation[recipients][]', options_for_select(User.where.not(id: current_user.id).map {|s| [s.identifier, s.id]}, params[:recipients]), :multiple => true, class: "form-control"
      .form-group
        %label= t('conversations.model.subject')
        = f.text_field :subject, class: "form-control"
      .form-group
        = f.hidden_field :body, id: :message_body
        %trix-editor{:input => "message_body"}

:javascript
  $( "#conversation_recipients_" ).select2({
  theme: "bootstrap",
  language: "#{current_user.language}"
  });

app/views/conversations/new.html.haml
.page-header
  %h2= t('.title')
= render partial: 'mailbox/folder_view', locals: { is_conversation: true }

app/views/conversations/show.html.haml
.page-header
  %h2= @receipts.first.message.subject.html_safe
  = content_for :title,  t('nightingale') + ' | ' + @receipts.first.message.subject.html_safe
= render 'mailbox/folders'
%br
= link_to icon('arrow-left'), mailbox_path, class: 'btn btn-default'
%br
%br
= form_for :message, url: reply_conversation_path(conversation) do |f|
  .row
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .panel.panel-default
        .panel-heading
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              - if conversation.is_trashed?(current_user)
                = link_to icon('undo'), untrash_conversation_path(conversation), class: 'btn btn-default', method: :post
              - else
                = link_to icon('trash'), trash_conversation_path(conversation), class: 'btn btn-default', method: :post, |
                  data: {confirm: t('devise.registrations.edit.are_you_sure')} |
              .pull-right= f.button icon('reply'), class: 'btn btn-default'


        .panel-footer
          .form-group
            = f.hidden_field :body, id: :message_body
            %trix-editor{:input => "message_body"}
          .clearfix
        .panel-body
          - @receipts.each do |receipt|
            - message = receipt.message
            .media
              .media-body
                .row
                  .col-lg-2.col-md-2.col-sm-2.col-xs-4
                    %center
                      .widewrapper= image_tag(avatar_thumb(message.sender))
                  .col-lg-10.col-md-10.col-sm-10.col-xs-8
                    %h4.media-heading
                      = message.sender.name
                      %br/
                      %small
                        = t('conversations.model.date')
                        =l message.created_at, format: :long
                    = message.body.html_safe