config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :forms do
    resources :submissions
  end
  resources :domains
  resources :abilities
  resources :abilitysets
  resources :masteries
  resources :contacts, path: '/account/contacts'
  resources :links
  resources :locations
  resources :events do
    collection do
      get 'list'
      get 'tasks'
      get 'calendar'
      get 'log'
      get ':id/participants', to: 'events#participants', as: :participants
      get ':id/login',  to: 'events#login',  as: :login
      get ':id/logout', to: 'events#logout', as: :logout
      patch ':id/login',  to: 'events#login_update', as: :login_update
      patch ':id/logout',  to: 'events#logout_update', as: :logout_update
      patch 'login',  to: 'events#login_updates', as: :login_updates
      patch 'logout',  to: 'events#logout_updates', as: :logout_updates
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      delete :empty_trash
    end
  end

  resources :notes
  get 'dashboard/index'
  get 'conversations/load_messages'
  get "mail" => "mailbox#inbox", as: :mailbox
  get "mail/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mail/sent" => "mailbox#sent", as: :mailbox_sent
  get "mail/trash" => "mailbox#trash", as: :mailbox_trash

  resources :users do
    member do
      put :activate
      put :deactivate
      get :mastery
      get :contacts
      put :update_mastery
    end
  end
  devise_for :users, :path => '/account'
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      root :to => 'dashboard#index'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :knows
  belongs_to :mastery, optional: true
  belongs_to :role, optional: true
  has_many :abilities,  -> { distinct }, through: :knows
  accepts_nested_attributes_for :knows, reject_if: :all_blank
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable, :lockable
  mount_uploaders :avatars, AvatarUploader
  has_many :notes
  has_many :contacts
  has_many :events
  has_many :user_submissions
  has_many :submissions, through: :user_submissions
  before_save :clean_up
  validate :check_demo
  validates_presence_of :email
  acts_as_messageable
  belongs_to :domain, optional: true
  scope :domained, ->(u) { where("users.domain_id = ?", u.domain_id) if u.domain_id.present? }
  scope :domained_students, ->(u) { where("users.domain_id = ? and users.account_type = ?", u.domain_id, "student") if u.domain_id.present? }
  scope :domained_preceptors, ->(u) { where("users.domain_id = ? and users.account_type = ?", u.domain_id, "preceptor") if u.domain_id.present? }
  scope :domained_faculty, ->(u) { where("users.domain_id = ? and users.account_type = ?", u.domain_id, "faculty") if u.domain_id.present? }
  scope :domained_administrators, ->(u) { where("users.domain_id = ? and users.account_type = ?", u.domain_id, "administrator") if u.domain_id.present? }
  scope :domained_overseers, ->(u) { where("users.domain_id = ? and (users.account_type = ? or users.account_type = ?)", u.domain_id, "faculty", "preceptor") if u.domain_id.present? }

  def name
    result = ''
    empty = false
    I18n.t('name.format.default').split('').each do |e|
      case e
      when 'P'
        if !self.prefix.empty?
          result += self.prefix
        else
          empty = true
        end
      when 'F'
        if !self.first_name.empty?
          result += self.first_name
        else
          empty = true
        end
      when 'M'
        if !self.middle_name.empty?
          result += self.middle_name
        else
          empty = true
        end
      when 'L'
        if !self.last_name.empty?
          result += self.last_name
        else
          empty = true
        end
      when 'S'
        if !self.suffix.empty?
          result += self.suffix
        else
          empty = true
        end
      else
        if !empty
          result += e
        else
          empty = false
        end
      end
    end
    result.strip
  end

  def identifier
    buffer = '/'
    buffer += self.domain.namespace if self.domain
    buffer += "/"
    buffer += self.role.identifier if self.role
    buffer += "/"
    buffer += "#{self.name} : " unless self.name.blank?
    buffer += "#{self.email}"
    buffer
  end

  def has_power?
    self.account_type.to_s == 'superuser' ||
    self.account_type.to_s == 'administrator' ||
    self.account_type.to_s == 'faculty'
  end

  def admin?
    self.account_type.to_s == 'administrator' ||
      self.account_type.to_s == 'superuser'
  end

  def superuser?
    self.account_type.to_s == 'superuser'
  end

  def overseer?
    self.account_type.to_s == 'preceptor' ||
    self.account_type.to_s == 'faculty' ||
    self.account_type.to_s == 'administrator' ||
    self.account_type.to_s == 'superuser'
  end

  def preceptor?
    self.account_type.to_s == 'preceptor'
  end

  def student?
    self.account_type.to_s == 'student'
  end

  def faculty?
    self.account_type.to_s == 'faculty'
  end

  def active_for_authentication?
    super and self.active
  end

  def inactive_message
    if !self.active
      I18n.t('devise.failure.inactive', locale: self.language)
    end
  end

  def account
    I18n.t(account_type.to_s.blank? ? 'undefined' : account_type)
  end

  def level_up!
    if self.mastery
      level_value = self.mastery.get_levelup(self.id)
      if level_value > self.level
        self.level = level_value
        self.save!
      end
    end
  end

  def use_events?
    self.role && self.role.use_events
  end

  def use_notes?
    self.role && self.role.use_notes
  end

  def events_has_calendar?
    self.role && self.role.events_has_calendar
  end

  def events_overseer?
    self.role && self.role.events_overseer
  end

  def events_has_tasks?
    self.role && self.role.events_has_tasks
  end

  def events_has_log?
    self.role && self.role.events_has_log
  end

  def events_create_edit?
    self.role && self.role.events_create_edit
  end

  def events_sign_in?
    self.role && self.role.events_sign_in
  end

  def use_mail?
    self.role && self.role.use_mail
  end

  def use_user_directory?
    self.admin? || (self.role && self.role.use_user_directory)
  end

  def use_links?
    self.role && self.role.use_links
  end

  def links_create_edit?
    self.role && self.role.links_create_edit
  end

  def use_locations?
    self.role && self.role.use_locations
  end

  def use_mastery_builder?
    self.role && self.role.use_mastery_builder
  end

  def has_mastery?
    self.role && self.role.has_mastery
  end

  def mastery_rank_up?
    self.role && self.role.mastery_rank_up
  end

  def use_form_builder?
    self.role && self.role.use_form_builder
  end

  def use_forms?
    self.role && self.role.use_forms
  end

  def view_submitted_forms?
    self.role && self.role.view_submitted_forms
  end



  def self.search(term)
    where('first_name ILIKE ANY (array[:terms]) or last_name ILIKE ANY (array[:terms]) or email ILIKE ANY (array[:terms])', terms: term.split.map {|val| "%#{val}%" })
  end

  private

  def clean_up

    # clean up fields
    self.prefix = self.prefix.to_s.strip
    self.first_name = self.first_name.to_s.strip
    self.middle_name = self.middle_name.to_s.strip
    self.last_name = self.last_name.to_s.strip
    self.suffix = self.suffix.to_s.strip
    self.email = self.email.downcase.to_s.strip
    self.extid = self.extid.to_s.strip
    self.birthdate = Date.new(1970, 1, 1) if self.birthdate.nil?
    # if they're a student set the level
    if self.student?
      self.level = 1 unless self.level.to_i > 0
    end

    # if they're a overseer make them a pin number
    #if self.overseer?
    #  self.pin = (0...6).map { (48 + rand(10)).chr }.join if self.pin.empty?
    #end
  end

  def check_demo
    if (self.domain && self.domain.demo) && User.domained_students(self).count >= 10
      errors.add :base, I18n.t('student_limit_exceeded', scope: [:domains, :messages])
    end

  end

  def mailboxer_email(object)
    self.email
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update_mastery, :mastery, :show, :edit, :update, :destroy, :activate, :deactivate, :information, :contacts]
  before_action :admin?, only: [:new, :edit, :create, :destroy, :active, :deactivate]
  before_action :usable?
  before_action :has_mastery, only: [:mastery]
  def mastery
    @knows = @user.knows
  end


  def contacts
  end

  def update_mastery
    if current_user.mastery_rank_up?
      knows = Know.where(id: params[:know_ids])
      knows.update_all('proficiency = proficiency + 1')
      if knows.collect {|k| k.ability.proficiency_level <= k.proficiency}.all?
        @user.level_up!
      end
      flash[:notice] = t('.notice')
      redirect_to mastery_user_path
    else
      flash[:error] = t('.error')
      redirect_to mastery_user_path
    end
  end

  def index
    if current_user.superuser?
      if params[:search] && !params[:search].blank?
        @users = User.search(params[:search]).order("created_at DESC").page(params[:page]).per(8)
      else
        @users = User.all.order("created_at DESC").page(params[:page]).per(8)
      end
    else
      if params[:search] && !params[:search].blank?
        @users = User.domained(current_user).search(params[:search]).order("created_at DESC").page(params[:page]).per(8)
      else
        @users = User.domained(current_user).order("created_at DESC").page(params[:page]).per(8)
      end
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    super_safe
  end

  def create
    @user = User.new(user_params)
    @user.password = @user.birthdate.nil? ? Date.new(1970, 1, 1).strftime('%F') : @user.birthdate.strftime('%F')
    @user.skip_confirmation!
    @user.active = true
    if @user.save
      redirect_to @user, notice: t('.notice')
    else
      render :new
    end
  end

  def update
    super_safe
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to @user, notice: t('.notice') }
        format.js {render inline: "location.reload();" }
      end
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: t('.notice')
    end
  end

  def activate
    if @user.update(active: true)
      redirect_back(fallback_location: users_path, notice: t('.notice'))
    end
  end

  def deactivate
    if @user.update(active: false)
      redirect_back(fallback_location: users_path, notice: t('.notice'))
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def admin?
    if !current_user.admin?
      redirect_to users_path, :flash => { :danger => t('access_denied') }
    end
  end

  def super_safe
    if @user.superuser? && !current_user.superuser?
      redirect_to users_path, :flash => { :danger => t('access_denied') }
    end
  end

  def has_mastery
    unless @user.has_mastery?
      redirect_to users_path, :flash => { :danger => t('.no_mastery') }
    end
  end

  def usable?
    unless current_user.use_user_directory?
      redirect_to root_path, :flash => { :danger => t('access_denied') }
    end
  end
  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:prefix, :first_name, :middle_name, :last_name, :suffix, :language, :account_type, :extid, :level, :timezone, :email, :birthdate, :mastery_id, :domain_id, :role_id, {avatars: []}, :avatars_cache
)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user)
    user.avatars.empty? ? 'default.png' : user.avatars.last.url
  end

  # def avatar_xxhdpi(user)
  #   user.avatars.empty? ? 'xxhdpi_default.png' : user.avatars.last.xxhdpi.url
  # end

  def avatar_thumb(user)
    user.avatars.empty? ? 'ldpi_default.png' : user.avatars.last.ldpi.url
  end
end

app/views/users/_form.html.haml
= form_for @user, :html => { :multipart => true } do |f|
  - if @user.errors.any?
    #error_explanation
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .actions
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        = link_to icon('arrow-left'), users_path, class: 'btn btn-default'
        .pull-right= f.button icon('save').html_safe, class: 'btn btn-default'
    %br
  .form-group
    = f.label :prefix
    %br/
    = f.text_field :prefix, class: 'form-control'
  .form-group
    = f.label :first_name
    %br/
    = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :middle_name
    %br/
    = f.text_field :middle_name, class: 'form-control'
  .form-group
    = f.label :last_name
    %br/
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :suffix
    %br/
    = f.text_field :suffix, class: 'form-control'
  .form-group
    = f.label :language
    %br/
    = f.select :language, options_for_select(locale_name_pairs, (@user.new_record? ? current_user.domain.language.to_s : @user.language.to_s)), {}, {class: 'form-control'}
  .form-group
    = f.label :timezone
    %br/
    = f.collection_select :timezone, ActiveSupport::TimeZone.all, :name, :to_s, { selected: (@user.new_record? ? current_user.domain.timezone.to_s : @user.timezone.to_s) }, class: 'form-control'
  .form-group
    = f.label :birthdate
    = f.date_select :birthdate
  .form-group
    = f.label :level
    %br/
    = f.number_field :level, class: 'form-control', value: (@user.new_record? ? current_user.domain.student_starting_level.to_i : @user.level)
  .form-group
    = f.label :extid
    = f.text_field :extid, class: 'form-control'
  -if @user.id != current_user.id
    .form-group
      = f.label :account_type
      = f.select :account_type, [[t('student'), 'student'],[t('preceptor'), 'preceptor'],[t('faculty'), 'faculty'],[t('administrator'), 'administrator']], |
      {:selected => @user.account_type}, {:class => 'form-control'}
  -if current_user.superuser?
    .form-group
      = f.label :domain
      = f.select :domain_id, options_from_collection_for_select(Domain.all, :id, :identifier), {}, class: 'form-control'
  -elsif @user.domain_id.to_i == 0 || @user.new_record?
    .field
      = f.hidden_field :domain_id, value: current_user.domain_id
  .form-group
    = f.label :role
    %br/
    = f.select :role_id, options_from_collection_for_select(Role.domained(current_user), :id, :identifier, @user.role_id), {}, class: 'form-control'
  .form-group
    = f.label :avatar
    .input-group
      %span.input-group-btn
        %span.btn.btn-default{:onclick => "$(this).parent().find('input[type=file]').click();"}
          = icon('file-image-o')
        = f.file_field :avatars, multiple: true, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;"
        = f.hidden_field :avatars_cache
      %span.form-control
  .form-group
    = f.label :mastery
    %br/
    = f.select :mastery_id, options_from_collection_for_select(Mastery.domained(current_user), :id, :identifier, @user.mastery_id), {}, class: 'form-control'
  .form-group
    = f.label :email
    %br/
    = f.email_field :email, class: 'form-control'
    = @user.current_password
%br

app/views/users/contacts.html.haml
.page-header
  %h2= t('.title')
.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    - ref = request.headers["HTTP_REFERER"]
    - if ref && ref.include?('users/')
      - back = session[:user_back]
    - elsif ref
      - session[:user_back] = ref
      - back = session[:user_back]
    -else
      - back = users_path
    .btn-group
      = link_to icon('arrow-left'), back, class: 'btn btn-default'
      = link_to icon('address-book'), contacts_user_path, class: 'btn btn-default active'
      = link_to icon('graduation-cap'), mastery_user_path, class: 'btn btn-default' if @user.has_mastery?
      = link_to icon('eye'), user_path, class: 'btn btn-default'
    -if current_user.admin? && @user.id != current_user.id
      .pull-right= link_to icon('edit'), edit_user_path(@user), class: 'btn btn-default'
    -elsif @user.id == current_user.id
      .pull-right= link_to icon('edit'), edit_user_registration_path, class: 'btn btn-default'
%br
.form-group
  %center
    %p= @user.identifier
%br
-if current_user.use_mail? && @user.use_mail?
  .row
    .col-lg-12
      =link_to(new_conversation_path(recipients: @user.id), class: 'btn btn-block btn-default') do
        =icon('envelope')
        &nbsp;
        = @user.identifier
      %br
- @user.contacts.each do |contact|
  .row
    .col-lg-12
      =contact.to_button
      %br

app/views/users/edit.html.haml
.page-header
  %h2= t('.title')

= render 'form'

app/views/users/index.html.haml
.page-header
  %h2= t('.title')

= form_tag(users_path, :method => "get", id: "search-form") do
  .row
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .input-group
        %span.input-group-btn
          = link_to icon('arrow-left'), dashboard_index_path, class: 'btn btn-default'
        = text_field_tag :search, params[:search], placeholder: t('.search'), class: 'form-control'
        %span.input-group-btn
          = button_tag icon('search'), class: 'btn btn-default'
          = link_to icon('plus'), new_user_path, class: 'btn btn-default' if current_user.admin?
%br
-if params[:search] && @users.count == 0
  .well
    %center
      = t('.no_found')
-else
  -@users.each_slice(2) do |users|
    .row
      -users.each do |user|
        .col-lg-6.col-md-12.col-sm-12.col-xs-12
          .panel.panel-default
            .panel-heading
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  .panel-title-ellipse= user.identifier
              %br
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  - if current_user.superuser?
                    =trash_button(user)
                  .pull-right
                    .btn-group
                      -if user.id != current_user.id && current_user.admin?
                        -if user.active
                          = link_to(icon('dot-circle-o'), deactivate_user_path(user), :method => :put, :confirm => t('devise.registrations.edit.are_you_sure'), class: 'btn btn-default')
                        -else
                          = link_to(icon('circle-o'), activate_user_path(user), :method => :put, :confirm => t('devise.registrations.edit.are_you_sure'), class: 'btn btn-default')
                      = link_to icon('address-book'), contacts_user_path(user), class: 'btn btn-default'
                      = link_to icon('graduation-cap'), mastery_user_path(user), class: 'btn btn-default' if user.has_mastery?
                      = link_to icon('eye'), user, class: "btn btn-default"
                      - if current_user.admin?
                        = link_to icon('edit'), edit_user_path(user), class: 'btn btn-default'


            .panel-body
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  %center
                    .form-group
                      .widewrapper= link_to image_tag(avatar_thumb(user)), user


.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    = paginate @users

app/views/users/mastery.html.haml
.page-header
  %h2= t('.title')

= form_tag update_mastery_user_path, method: :put do
  .row
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      - ref = request.headers["HTTP_REFERER"]
      - if ref && ref.include?('users/')
        - back = session[:user_back]
      - elsif ref
        - session[:user_back] = ref
        - back = session[:user_back]
      -else
        - back = users_path
      .btn-group
        = link_to icon('arrow-left'), back, class: 'btn btn-default'
        = link_to icon('address-book'), contacts_user_path, class: 'btn btn-default'
        = link_to icon('graduation-cap'), mastery_user_path, class: 'btn btn-default active'
        = link_to icon('eye'), user_path, class: 'btn btn-default'
      .pull-right
        -if (current_user.mastery_rank_up? && current_user.id != @user.id)
          = button_tag(type: 'submit', class: "btn btn-default") do
            = icon('level-up')
  %br
  .form-group
    %center
      %p= @user.identifier
  %br
  .form-group
    -@knows.each do |know|
      .panel.panel-default
        .panel-heading
          = know.ability.identifier
          .pull-right= check_box_tag "know_ids[]", know.id if (current_user.mastery_rank_up? && current_user.id != @user.id)
        .panel-body
          .progress
            .progress-bar.progress-bar-striped{class: "#{know.bar}", "aria-valuemax" => "#{know.maxvalue}", |
            "aria-valuemin" => "0", "aria-valuenow" => "#{know.value}",   |
            :role => "progressbar",                                             |
            :style => "width: #{know.width}%; min-width: 2em;"}
              %span= know.bartext

app/views/users/new.html.haml
.page-header
  %h2= t('.title')

= render 'form'

app/views/users/show.html.haml
.page-header
  %h2= t('.title')
.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    - ref = request.headers["HTTP_REFERER"]
    - if ref && ref.include?('users/')
      - back = session[:user_back]
    - elsif ref
      - session[:user_back] = ref
      - back = session[:user_back]
    -else
      - back = users_path
    .btn-group
      = link_to icon('arrow-left'), back, class: 'btn btn-default'
      = link_to icon('address-book'), contacts_user_path, class: 'btn btn-default'
      = link_to icon('graduation-cap'), mastery_user_path, class: 'btn btn-default' if @user.has_mastery?
      = link_to icon('eye'), user_path, class: 'btn btn-default active'
    -if current_user.admin?
      .pull-right= link_to icon('edit'), edit_user_path(@user), class: 'btn btn-default'
    -elsif @user.id == current_user.id
      .pull-right= link_to icon('edit'), edit_user_registration_path, class: 'btn btn-default'
%br
.form-group
  %center
    .widewrapper= image_tag avatar(@user)
    %br
    %p= @user.identifier
-if current_user.admin? || @user.id == current_user.id
  .form-group
    %label= User.human_attribute_name :prefix
    .form-control.wrapped= @user.prefix
  .form-group
    %label= User.human_attribute_name :first_name
    .form-control.wrapped= @user.first_name
  .form-group
    %label= User.human_attribute_name :middle_name
    .form-control.wrapped= @user.middle_name
  .form-group
    %label= User.human_attribute_name :last_name
    .form-control.wrapped= @user.last_name
  .form-group
    %label= User.human_attribute_name :suffix
    .form-control.wrapped= @user.suffix
.form-group
  %label= User.human_attribute_name :language
  .form-control.wrapped= code2language(@user.language)
.form-group
  %label= User.human_attribute_name :timezone
  .form-control.wrapped= t('timezones' + '.' + @user.timezone)
-if current_user.has_power? || @user.id == current_user.id
  .form-group
    %label= User.human_attribute_name :birthdate
    .form-control.wrapped= l @user.birthdate unless @user.birthdate.nil?
-if @user.student? || current_user.has_power?
  .form-group
    %label= User.human_attribute_name :level
    .form-control.wrapped= @user.level
-if current_user.has_power? || @user.id == current_user.id
  .form-group
    %label= User.human_attribute_name :extid
    .form-control.wrapped= @user.extid
.form-group
  %label= User.human_attribute_name :account_type
  .form-control.wrapped= @user.account
.form-group
  %label= User.human_attribute_name :role
  .form-control.wrapped= @user.role.identifier if @user.role
-if @user.student?
  .form-group
    %label= User.human_attribute_name :mastery
    .form-control.wrapped= @user.mastery.title unless @user.mastery.nil?
.form-group
  %label= User.human_attribute_name :email
  .form-control.wrapped= @user.email