config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :forms do
    resources :submissions
  end
  resources :domains
  resources :abilities
  resources :abilitysets
  resources :masteries
  resources :contacts, path: '/account/contacts'
  resources :links
  resources :locations
  resources :events do
    collection do
      get 'list'
      get 'tasks'
      get 'calendar'
      get 'log'
      get ':id/participants', to: 'events#participants', as: :participants
      get ':id/login',  to: 'events#login',  as: :login
      get ':id/logout', to: 'events#logout', as: :logout
      patch ':id/login',  to: 'events#login_update', as: :login_update
      patch ':id/logout',  to: 'events#logout_update', as: :logout_update
      patch 'login',  to: 'events#login_updates', as: :login_updates
      patch 'logout',  to: 'events#logout_updates', as: :logout_updates
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      delete :empty_trash
    end
  end

  resources :notes
  get 'dashboard/index'
  get 'conversations/load_messages'
  get "mail" => "mailbox#inbox", as: :mailbox
  get "mail/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mail/sent" => "mailbox#sent", as: :mailbox_sent
  get "mail/trash" => "mailbox#trash", as: :mailbox_trash

  resources :users do
    member do
      put :activate
      put :deactivate
      get :mastery
      get :contacts
      put :update_mastery
    end
  end
  devise_for :users, :path => '/account'
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      root :to => 'dashboard#index'

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  #belongs_to :overseer, class_name: 'User', foreign_key: :overseer_id
  #belongs_to :student, class_name: 'User', foreign_key: :student_id
  belongs_to :location
  belongs_to :abilityset
  belongs_to :domain
  belongs_to :user
  #belongs_to :student_evaluation, class_name: 'Submission', foreign_key: 'student_evaluation_id', optional: true
  #belongs_to :overseer_evaluation, class_name: 'Submission', foreign_key: 'overseer_evaluation_id', optional: true
  #belongs_to :overseer_agreement, class_name: 'Submission', foreign_key: 'overseer_agreement_id', optional: true
  validates_presence_of :start
  validates_presence_of :stop
  scope :domained, ->(u) { where("events.domain_id = ?", u.domain_id) if u.domain_id.present? }
  #before_save :link_agreement
  has_many :participants
  has_many :users, through: :participants
  accepts_nested_attributes_for :participants, reject_if: :all_blank, allow_destroy: true

  def part_of?(user)
    self.participants.exists?(user_id: user.id)
  end

  def start_time
    start
  end




  def link_agreement
    if self.overseer_agreement.nil? && self.domain &&
       self.domain.overseer_agreement_form_fill.to_s == 'until_expired'  &&
       self.domain.overseer_agreement_form

      party_ids = UserSubmission.where(user_id: [overseer_id]).distinct.pluck(:submission_id) &
                  UserSubmission.where(user_id: [student_id]).distinct.pluck(:submission_id)

      possible =  Submission.where(form_id: self.domain.overseer_agreement_form_id, id: party_ids)
                    .joins(:form_fields).where(form_fields: { field_type: 'agreement_expiration'})
                    .joins(:text_responses).where("to_date(text_responses.answer, 'YYYY MM DD') > ?", self.stop.to_date).distinct

      with_ability = possible.joins(:abilityset_submissions).where(abilityset_submissions: {abilityset_id: self.abilityset_id}).distinct

      self.overseer_agreement = with_ability.count == 0 ? possible.first : with_ability.first
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :login, :logout, :login_update, :logout_update, :participants]
  before_action :set_events, only: [:calendar]
  before_action :has_power?, only: [:new, :create, :edit, :update, :destroy]
  before_action :usable?
  after_action :check_has?, only: [:create, :update]

  # GET /events
  # GET /events.json
  def index
    if session[:event_view]
      redirect_to session[:event_view]
    else
      session[:event_view] = calendar_events_path
      redirect_to session[:event_view]
    end
  end

  def list
    session[:event_view] = list_events_path
    if params[:date]
      point = Time.zone.parse(params[:date])
    else
      point = Time.zone.now
    end
    b = point.beginning_of_day.utc
    e = point.end_of_day.utc

    if current_user.superuser?
      @events = Event.where('start between ? and ?', b, e).page(params[:page]).per(8)
    else
      @events = Event.domained(current_user).joins(:participants).where('participants.user_id = ? or events.user_id = ?', current_user.id, current_user.id).where('(start between ? and ?)', b, e).distinct.page(params[:page]).per(8)
    end
  end

  def tasks
    session[:event_view] = tasks_events_path
    @events = Participant.includes(:event).where('(participants.user_id = ? OR events.user_id = ?)', current_user.id, current_user.id).order('events.start').references(:event).distinct.page(params[:page]).per(8)
  end

  def calendar
    session[:event_view] = calendar_events_path
  end

  def log
    session[:event_view] = log_events_path
    @events = Participant.includes(:event).where('(participants.completed = false) AND (participants.user_id = ? OR events.user_id = ?)', current_user.id, current_user.id).order('events.start').references(:event).distinct.page(params[:page]).per(8)

  end

  def login
    involved?(@event)
  end

  def logout
    involved?(@event)
  end

  def login_updates
    h = Participant.where(id: params[:participant][:id]).first
    if h
      involved?(h.event)
      h.update_attributes(login: DateTime.now())
      redirect_to tasks_events_path, notice: t('.notice')
    end
  end

  def logout_updates
    h = Participant.where(id: params[:participant][:id]).first
    if h
      involved?(h.event)
      h.update_attributes(logout: DateTime.now())
      h.check_complete?
      redirect_to tasks_events_path, notice: t('.notice')
    end
  end

  def login_update
    involved?(@event)
    h = Participant.where(id: params[:participant][:id]).first
    if h
      h.update_attributes(login: DateTime.now())
      h.check_complete?
      redirect_to participants_events_path(@event), notice: t('.notice')
    end
  end

  def logout_update
    involved?(@event)
    h = Participant.where(id: params[:participant][:id]).first
    if h
      h.update_attributes(logout: DateTime.now())
      h.check_complete?
      redirect_to participants_events_path(@event), notice: t('.notice')
    end
  end

  def participants
  end

  # GET /events/1
  # GET /events/1.json
  def show
    involved?(@event)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t('.notice') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_events
    if current_user.superuser?
      @events = Event.all
    else
      @events = Event.domained(current_user).joins(:participants).where('participants.user_id = ? or events.user_id = ?', current_user.id, current_user.id).distinct
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:overseer_id, :student_id, :location_id, :start, :stop, :login, :logout, :user_id, :abilityset_id, :domain_id, :student_evaulation_id, :overseer_evaluation_id, :overseer_agreement_id, participants_attributes: Participant.attribute_names.map(&:to_sym).push(:tex).push(:_destroy))
  end

  def involved?(e)
    unless (e.part_of?(current_user) || current_user.admin?)
      redirect_to events_path, :flash => { :danger => t('access_denied') }
    end
  end

  def check_has?
    if @event.abilityset
      @event.users.each do |u|
        if u.has_mastery?
          @event.abilityset.abilities.each do |ability|
            ability.knows.where(user_id: u.id).first_or_create
          end
        end
      end
    end
  end

  def has_power?
    unless current_user.events_create_edit?
      redirect_to events_path, :flash => { :danger => t('access_denied') }
    end
  end

  def usable?
    unless current_user.use_events?
      redirect_to root_path, :flash => { :danger => t('access_denied') }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper


  def within(e, h)
    start = e.start.utc
    stop = e.stop.utc
    now = DateTime.now.utc
    margin = (e && e.domain && e.domain.time_margin) ? e.domain.time_margin.to_i.minutes : 15.minutes
    result = 'default'
    # logged in on time
    if h.login && (start + margin) > h.login && h.login > (start - margin)
      result = 'success'

      # logout on time
      if h.logout && (stop + margin) > h.logout && h.logout > (stop - margin)
        result = 'success'
      # logged out but late
      elsif h.logout && !((stop + margin) > h.logout && h.logout > (stop - margin))
        result = 'danger'
      # not logged out and safe to log out
      elsif h.logout.nil? && (stop + margin) > now && now > (stop - margin)
        result = 'warning'
      # not logged out and late
      elsif h.logout.nil? && (stop + margin) < now
        result = 'danger'
      end
    # logged in but late
    elsif h.login && !((start + margin) > h.login && h.login > (start - margin))
      result = 'danger'
    # not logged in and safe to log in
    elsif h.login.nil? && (start + margin) > now && now > (start - margin)
      result = 'warning'
    # not logged in and late
    elsif h.login.nil? && (start + margin) < now
      result = 'danger'
    end

    result
  end


end

app/views/events/_entry.html.haml
.panel.panel-default
  /{:class => "panel-{within(event)}"}
  .panel-heading.clearfix
    = trash_button(event) if current_user.events_create_edit?
    .pull-right
      .btn-group
        /-if current_user.id == event.overseer.id && event.domain.overseer_agreement_form && event.overseer_agreement.nil? && event.domain.overseer_agreement_form_fill != "no"
        /  = link_to icon('shield'), new_form_submission_path(event.domain.overseer_agreement_form, overseer_agreement: event.id), class: 'btn btn-default'
        /-if current_user.id == event.overseer.id && event.domain.overseer_form && event.login && event.student_evaluation.nil? && event.domain.overseer_form_fill != "no"
        /  = link_to icon('wpforms'), new_form_submission_path(event.domain.overseer_form, overseer_form: event.id), class: 'btn btn-default'
        /-if current_user.id == event.student.id && event.domain.student_form && event.login && event.overseer_evaluation.nil? && event.domain.student_form_fill != "no"
        /  = link_to icon('wpforms'), new_form_submission_path(event.domain.student_form, student_form: event.id), class: 'btn btn-default'
        /-if current_user.id == event.overseer.id
        /  = link_to icon('address-book'), contacts_user_path(event.student), class: 'btn btn-default'
        /-if current_user.id == event.student.id
        /  = link_to icon('address-book'), contacts_user_path(event.overseer), class: 'btn btn-default'
        = link_to icon('graduation-cap'), mastery_user_path(current_user), class: 'btn btn-default' if (current_user.has_mastery? && event.part_of?(current_user))
        = link_to icon('location-arrow'), event.location.navigate, target: :_blank, class: 'btn btn-default'
        = link_to icon('users'), participants_events_path(event), class: 'btn btn-default'
        = link_to icon('eye'), event, class: 'btn btn-default'
        = link_to icon('edit'), edit_event_path(event), class: 'btn btn-default' if current_user.events_create_edit?
  .panel-body
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %center
          %label= Event.human_attribute_name :start
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %center
          %label= Event.human_attribute_name :stop
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %center
          = l event.start, format: :long
        %br
      .col-lg-6.col-md-6.col-sm-6.col-xs-6
        %center
          = l event.stop, format: :long
        %br
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        %center
          %label= Event.human_attribute_name :location
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        %center
          = link_to event.location.identifier, event.location.navigate, target: :_blank
        %br



    /%center
    /  %label= Event.human_attribute_name :student
    /.col-lg-6.col-md-6.col-sm-6.col-xs-6
    /%center
    /  %label= Event.human_attribute_name :overseer
    /.row
    /  .col-lg-6.col-md-6.col-sm-6.col-xs-6
    /    %center
    /      /= link_to event.student.identifier, event.student
    /      %br
    /      /.widewrapper= link_to image_tag(avatar_thumb(event.student)), event.student
    /      %br
    /  .col-lg-6.col-md-6.col-sm-6.col-xs-6
    /    %center
    /      /= link_to event.overseer.identifier, event.overseer
    /      %br
    /      /.widewrapper= link_to image_tag(avatar_thumb(event.overseer)), event.overseer
    /      %br
    /.row
    /  .col-lg-6.col-md-6.col-sm-6.col-xs-6
    /    %center
    /      /- if event.login
    /      /  %label= Event.human_attribute_name :login
    /      /  %br
    /      /  = l event.login.in_time_zone(current_user.timezone), format: :long
    /      /- else
    /      /  = link_to icon('sign-in'), login_events_path(event), class: 'btn btn-default'
    /  .col-lg-6.col-md-6.col-sm-6.col-xs-6
    /    %center
    /      /- if event.logout
    /      /  %label= Event.human_attribute_name :logout
    /      /  %br
    /      /  = l event.logout.in_time_zone(current_user.timezone), format: :long
    /      /- else
    /      /  = link_to icon('sign-out'), logout_events_path(event), class: 'btn btn-default'

    /.row
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /- if event.student_evaluation && (current_user.has_power? || event.overseer_id == current_user.id)
    /      /  %label= Event.human_attribute_name :student_evaluation
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /- if event.overseer_agreement && (current_user.has_power? || event.overseer_id == current_user.id)
    /      /  %label= Event.human_attribute_name :overseer_agreement
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /- if event.overseer_evaluation && (current_user.has_power? || event.student_id == current_user.id)
    /      /  %label= Event.human_attribute_name :overseer_evaluation
    /.row
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /= link_to icon('wpforms'), form_submission_path(event.student_evaluation.form, event.student_evaluation), class: 'btn btn-default btn-block' if event.student_evaluation && (current_user.has_power? || event.overseer_id == current_user.id)
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /= link_to icon('shield'), form_submission_path(event.overseer_agreement.form, event.overseer_agreement), class: 'btn btn-default btn-block' if event.overseer_agreement && (current_user.has_power? || event.overseer_id == current_user.id)
    /  .col-lg-4.col-md-4.col-sm-4.col-xs-4
    /    %center
    /      /= link_to icon('wpforms'), form_submission_path(event.overseer_evaluation.form, event.overseer_evaluation), class: 'btn btn-default btn-block' if event.overseer_evaluation && (current_user.has_power? || event.student_id == current_user.id)
    /-if !event.login && event.start > Time.zone.now
    /  .row
    /    .col-lg-12.col-md-12.col-sm-12.col-xs-12
    /      %br
    /      %center.clearfix{id: "count#{event.id}"}
    /        :javascript
    /          $.countdown.setDefaults($.countdown.regionalOptions["#{t('js.countdown')}"]);
    /          jQuery(document).on('turbolinks:load', function() { $(function ()
    /          { $("#count#{event.id}").countdown({until: $.countdown.UTCDate(
    /          #{Time.zone.now.utc_offset/60},
    /          #{event.start.year},
    /          #{event.start.month-1},
    /          #{event.start.day},
    /          #{event.start.hour},
    /          #{event.start.min},
    /          #{event.start.sec}, 0), expiryUrl: "#{request.original_url}"}); }); });
    /-elsif event.login && !event.logout && event.stop > Time.zone.now
    /  .row
    /    .col-lg-12.col-md-12.col-sm-12.col-xs-12
    /      %br
    /      %center.clearfix{id: "count#{event.id}"}
    /        :javascript
    /          $.countdown.setDefaults($.countdown.regionalOptions["#{t('js.countdown')}"]);
    /          jQuery(document).on('turbolinks:load', function() { $(function ()
    /          { $("#count#{event.id}").countdown({until: $.countdown.UTCDate(
    /          #{Time.zone.now.utc_offset/60},
    /          #{event.stop.year},
    /          #{event.stop.month-1},
    /          #{event.stop.day},
    /          #{event.stop.hour},
    /          #{event.stop.min},
    /          #{event.stop.sec}, 0), expiryUrl: "#{request.original_url}"}); }); });

app/views/events/_task.html.haml
.panel{:class => "panel-#{(p.user.events_sign_in?) ? 'default' : within(p.event, p)}"}
  .panel-heading.clearfix
    = trash_button(p.event) if current_user.events_create_edit?
    .pull-right
      .btn-group
        = link_to icon('graduation-cap'), mastery_user_path(p.user), class: 'btn btn-default' if (p.user.has_mastery?) && (current_user.mastery_rank_up? || current_user.id == p.user.id)
        = link_to icon('location-arrow'), p.event.location.navigate, target: :_blank, class: 'btn btn-default'
        = link_to icon('users'), participants_events_path(p.event), class: 'btn btn-default'
        = link_to icon('eye'), p.event, class: 'btn btn-default'
        = link_to icon('edit'), edit_event_path(p.event), class: 'btn btn-default' if current_user.events_create_edit?
  .panel-body
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
        %center
          %label= Event.human_attribute_name :start
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
        %center
          %label= Event.human_attribute_name :stop
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
        %center
          = l p.event.start, format: :long
        %br
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
      .col-lg-4.col-md-4.col-sm-4.col-xs-4
        %center
          = l p.event.stop, format: :long
        %br
    .row
      .col-lg-4.col-xs-4
        -if p.login || (current_user.events_sign_in? && p.user != current_user) && !p.user.events_sign_in?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %center
                %label= Participant.human_attribute_name :login
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %center
                - if p.login
                  = l p.login, format: :long
                -else
                  = form_for p, :url => { :action => :login_updates }, remote: true do |f|
                    = f.hidden_field :id, value: p.id
                    = f.button icon('sign-in'), class: 'btn btn-default'
      .col-lg-4.col-xs-4
        %center
          = link_to image_tag(avatar_thumb(p.user)), p.user
          %br
          = link_to p.user.identifier, p.user
      .col-lg-4.col-xs-4
        -if p.logout || (current_user.events_sign_in? && p.user != current_user) && !p.user.events_sign_in?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %center
                %label= Participant.human_attribute_name :logout
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %center
                - if p.logout
                  = l p.logout, format: :long
                -else
                  = form_for p, :url => { :action => :logout_updates }, remote: true do |f|
                    = f.hidden_field :id, value: p.id
                    = f.button icon('sign-out'), class: 'btn btn-default'
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        %center
          %label= Event.human_attribute_name :location
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        %center
          = link_to p.event.location.identifier, p.event.location.navigate, target: :_blank
    -if current_user.id == p.user_id || current_user.view_submitted_forms?
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          %center
            %label= Participant.human_attribute_name :forms
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          -p.forms.each_slice(3) do |x|
            .btn-group-justified
              -x.each do |f|
                - s = p.filled(f)
                - if s
                  = link_to(form_submission_path(f, s), class: 'btn btn-success') do
                    = icon('wpforms')
                    = f.identifier
                -elsif current_user.id == p.user_id
                  = link_to(new_form_submission_path(f, participant: p.id), class: 'btn btn-default') do
                    = icon('wpforms')
                    = f.identifier
    -if (!p.login && p.event.start > Time.zone.now) || (p.login && !p.logout && p.event.stop > Time.zone.now)
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          %center
            %label= Participant.human_attribute_name :countdown
    -if !p.login && p.event.start > Time.zone.now
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          %center.clearfix{id: "count#{p.id}"}
            :javascript
              $.countdown.setDefaults($.countdown.regionalOptions["#{t('js.countdown')}"]);
              jQuery(document).on('turbolinks:load', function() { $(function ()
              { $("#count#{p.id}").countdown({until: $.countdown.UTCDate(
              #{Time.zone.now.utc_offset/60},
              #{p.event.start.year},
              #{p.event.start.month-1},
              #{p.event.start.day},
              #{p.event.start.hour},
              #{p.event.start.min},
              #{p.event.start.sec}, 0), expiryUrl: "#{request.original_url}"}); }); });
    -elsif p.login && !p.logout && p.event.stop > Time.zone.now
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          %center.clearfix{id: "count#{p.id}"}
            :javascript
              $.countdown.setDefaults($.countdown.regionalOptions["#{t('js.countdown')}"]);
              jQuery(document).on('turbolinks:load', function() { $(function ()
              { $("#count#{p.id}").countdown({until: $.countdown.UTCDate(
              #{Time.zone.now.utc_offset/60},
              #{p.event.stop.year},
              #{p.event.stop.month-1},
              #{p.event.stop.day},
              #{p.event.stop.hour},
              #{p.event.stop.min},
              #{p.event.stop.sec}, 0), expiryUrl: "#{request.original_url}"}); }); });

app/views/events/edit.html.haml
.page-header
  %h2= t('.title')

= render 'form'

app/views/events/participants.html.haml
.page-header
  %h2= t('.title')
.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    = link_to icon('arrow-left'), list_events_path(date: @event.start.to_date), class: 'btn btn-default'
    .pull-right= link_to icon('edit'), edit_event_path(@event), class: 'btn btn-default' if current_user.events_create_edit?

%br
- @event.participants.order(:id).group_by {|u| u.user.role}.each do |g, p|
  .row
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .row
        .col-lg-12
          %h4= g.identifier
  - p.each do |h|
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        .panel{:class => "panel-#{(h.user.events_sign_in?) ? 'default' : within(@event, h)}"}
          .panel-heading
            .row
              .col-lg-12.col-md-12.col-sm-12.col-xs-12
                = h.identifier
            %br
            .row
              .col-lg-12.col-md-12.col-sm-12.col-xs-12
                = link_to icon('graduation-cap'), mastery_user_path(h.user), class: 'btn btn-default' if h.user.has_mastery?
                .pull-right
                  = link_to icon('address-book'), contacts_user_path(h.user), class: 'btn btn-default'
          .panel-body
            .row
              .col-lg-4.col-xs-4
                -if h.login || (current_user.events_sign_in? && h.user != current_user) && !h.user.events_sign_in?
                  .row
                    .col-lg-12.col-md-12.col-sm-12.col-xs-12
                      %center
                        %label= Participant.human_attribute_name :login
                  .row
                    .col-lg-12.col-md-12.col-sm-12.col-xs-12
                      %center
                        - if h.login
                          = l h.login, format: :long
                        -else
                          = form_for h, :url => { :action => :login_update }, remote: true do |f|
                            = f.hidden_field :id, value: h.id
                            = f.button icon('sign-in'), class: 'btn btn-default'
              .col-lg-4.col-xs-4
                %center
                  = link_to image_tag(avatar_thumb(h.user)), h.user
                  %br
                  = link_to h.user.identifier, h.user
              .col-lg-4.col-xs-4
                -if h.logout || (current_user.events_sign_in? && h.user != current_user) && !h.user.events_sign_in?
                  .row
                    .col-lg-12.col-md-12.col-sm-12.col-xs-12
                      %center
                        %label= Participant.human_attribute_name :logout
                  .row
                    .col-lg-12.col-md-12.col-sm-12.col-xs-12
                      %center
                        - if h.logout
                          = l h.logout, format: :long
                        -else
                          = form_for h, :url => { :action => :logout_update }, remote: true do |f|
                            = f.hidden_field :id, value: h.id
                            = f.button icon('sign-out'), class: 'btn btn-default'
            -if current_user.id == h.user_id || current_user.view_submitted_forms?
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  %br
                  %center
                    %label= Participant.human_attribute_name :forms
            -if current_user.id == h.user_id || current_user.view_submitted_forms?
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  -h.forms.each_slice(3) do |x|
                    .btn-group-justified
                      -x.each do |f|
                        - s = h.filled(f)
                        - if s
                          = link_to(form_submission_path(f, s), class: 'btn btn-success') do
                            = icon('wpforms')
                            = f.identifier
                        -elsif current_user.id == h.user_id
                          = link_to(new_form_submission_path(f, participant: h.id), class: 'btn btn-default') do
                            = icon('wpforms')
                            = f.identifier